exp:
  name: test-dataset
data_loader:
  name: dataset.MultiCohortDataset
  batch_size:
    train: 64
    eval: 32
    test: 64
  data:
    train:
      # - [isruc, train]
      - [mros, train]
      # - [shhs, train]
      # - [ssc, train]
      # - [wsc, train]
    eval:
      # - [isruc, eval]
      - [mros, eval]
      # - [shhs, eval]
      # - [ssc, eval]
      # - [wsc, eval]
    test:
      # - [isruc, test]
      - [mros, test]
      # - [shhs, test]
      # - [ssc, test]
      # - [wsc, test]
  data_dir: ./data/processed_oak
  modalities: [eeg, eog, emg]
  num_classes: 5
  segment_length: 300 # Length in seconds
